### ISSUE TITLE
Preferences dialog not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by albertus82** [Albertus82/RouterLogger#2]
GTK 3.18.9-1ubuntu3.2 i386. Updating to SWT 4.6.3 solves the problem but breaks the compatibility with JRE 6. A workaround is to set the environment variable `SWT_GTK3=0`. See also: [Ubuntu 16 LTS - Eclipse window preferences not working properly](http://stackoverflow.com/questions/36827762/ubuntu-16-lts-eclipse-window-preferences-not-working-properly).

**Comment by Albertus82** [comment]
3bba7b390c931127a1ec8624ca4b9273e9de2948
